name: Deploy Payroll

on:
  push:
    branches:
      - quick

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: kokofibo
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/payroll

            git fetch origin
            git reset --hard origin/quick

            php artisan optimize:clear

            sudo chown -R www-data:www-data storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache

            php artisan optimize
